# Generated by Django 5.2.1 on 2025-05-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team_home', models.CharField(max_length=100)),
                ('team_away', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('score_home', models.IntegerField(default=0)),
                ('score_away', models.IntegerField(default=0)),
            ],
        ),
    ]
